// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4lcbpkhmhkEK27adhm0b2DhS_TUBxPc',
    appId: '1:1033806462367:web:ea90fabbdf060152fc11aa',
    messagingSenderId: '1033806462367',
    projectId: 'fir-project-cf513',
    authDomain: 'fir-project-cf513.firebaseapp.com',
    storageBucket: 'fir-project-cf513.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgQNoXYe_sPpaN6BTppkBbeonFuF0YCk',
    appId: '1:1033806462367:android:2be00ce58f09ab87fc11aa',
    messagingSenderId: '1033806462367',
    projectId: 'fir-project-cf513',
    storageBucket: 'fir-project-cf513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtd79TfV1hFyQaCnwfqmQwNe9VW9xM620',
    appId: '1:1033806462367:ios:304044c45e20424efc11aa',
    messagingSenderId: '1033806462367',
    projectId: 'fir-project-cf513',
    storageBucket: 'fir-project-cf513.appspot.com',
    iosBundleId: 'com.example.databaseApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtd79TfV1hFyQaCnwfqmQwNe9VW9xM620',
    appId: '1:1033806462367:ios:39e698ea91ecb14afc11aa',
    messagingSenderId: '1033806462367',
    projectId: 'fir-project-cf513',
    storageBucket: 'fir-project-cf513.appspot.com',
    iosBundleId: 'com.example.databaseApp1.RunnerTests',
  );
}
